<?php

namespace Drupal\swt_cookie_policy\Form;


use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class SwtCookiePolicyAlertSettingsForm extends ConfigFormBase {

  /**
   * Gets the configuration names that will be editable.
   *
   * @return array
   *   An array of configuration object names that are editable if called in
   *   conjunction with the trait's config() method.
   */
  protected function getEditableConfigNames() {
    return ['swt_cookie_policy.alert'];
  }

  /**
   * Returns a unique string identifying the form.
   *
   * @return string
   *   The unique string identifying the form.
   */
  public function getFormId() {
    return 'swt_cookie_policy_alert_settings_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = $this->config('swt_cookie_policy.alert');

    $form['accept_label'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Accept Label'),
      '#default_value'=> $config->get('accept_label'),
    ];
    $form['more_label'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Know more Label'),
      '#default_value'=> $config->get('more_label'),
    ];

    return parent::buildForm($form, $form_state);
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    parent::submitForm(
      $form,
      $form_state
    ); // TODO: Change the autogenerated stub

    $values = $form_state->getValues();
    $config = $this->config('swt_cookie_policy.alert');
    $config->set('accept_label', $values['accept_label']);
    $config->set('more_label', $values['more_label']);
    $config->save();
  }
}